network/core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('register/', views.UserCreateView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('perfil/novo', views.PerfilCreateView.as_view(), name='perfil_form'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('newpost/', views.NewPostView.as_view(), name='newpost'),
    path('like/', views.LikeView.as_view(), name='like'),
]

network/network/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

network/core/models.py
from django.db import models


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='likes', null=True)
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='likes', null=True)
    created_date = models.DateTimeField(auto_now_add=True)

class Perfil(models.Model):

    class Sexo:
        masc = 'M'
        fem = 'F'
        outr = 'O'
        CHOICES = (
            (masc, 'Masculino'),
            (fem, 'Feminino'),
            (outr, 'Outro'),
        )


    nome = models.CharField(max_length=100)
    foto = models.ImageField(upload_to='fotos', null=True)
    data_nascimento = models.DateField(null=True)
    sexo = models.CharField(max_length=1, null=True, choices=Sexo.CHOICES)
    cidade = models.CharField(max_length=100, null=True)
    estado = models.CharField(max_length=100, null=True)
    pais = models.CharField(max_length=100, null=True)
    ocupacao = models.CharField(max_length=100, null=True)
    user = models.OneToOneField('auth.User', on_delete=models.CASCADE, null=False)

network/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from . models import Perfil
from django.core.exceptions import ValidationError


class PerfilForm(forms.ModelForm):
    nome = forms.CharField(max_length=100)
    foto = forms.ImageField(required=False)
    data_nascimento = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date', 'class': 'form-control'})
    )
    sexo = forms.ChoiceField(choices=Perfil.Sexo.CHOICES)
    cidade = forms.CharField(max_length=100)
    estado = forms.CharField(max_length=100)
    pais = forms.CharField(max_length=100)
    ocupacao = forms.CharField(max_length=100)
    user = forms.HiddenInput()
    class Meta:
        model = Perfil
        fields = ["nome", "foto", "data_nascimento", "sexo", "cidade", "estado", "pais", "ocupacao"]

network/core/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.db import IntegrityError
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login

from rest_framework.views import APIView
from rest_framework.response import Response

from .models import Post, Like, Perfil

from .serializers import PostSerializer

from . import forms
# Create your views here.


class UserCreateView(TemplateView):
    template_name = 'core/register.html'


    def post(self, request, *args, **kwargs):
        form = forms.UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('core:perfil_form'))
        return render(request, 'core/register.html', {'form': form})
    

class LoginView(TemplateView):
    template_name = 'core/login.html'

    def post(self, request, *args, **kwargs):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is None:
            user = authenticate(request, email=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('core:home'))
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('core:home'))
        else:
            return render(request, 'core/login.html')

class HomeView(TemplateView):
    template_name = 'core/home.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        posts = Post.objects.all()

        serializer = PostSerializer(list(posts), many=True, context={'request': self.request})
        ctx['posts'] = json.dumps(serializer.data)
        return ctx

class PerfilCreateView(TemplateView):
    template_name = 'core/perfil_form.html'

    def post(self, request, *args, **kwargs):
        form = forms.PerfilForm(request.POST)
        if form.is_valid():
            form.instance.user = request.user
            try:
                form.save()
            except IntegrityError:
                return render(request, 'core/perfil_form.html', {'form': form, 'error': 'Perfil já cadastrado'})
            return HttpResponseRedirect(reverse('core:home'))
        return render(request, 'core/perfil_form.html', {'form': form})
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['form'] = forms.PerfilForm()
        return ctx
    

class NewPostView(APIView):

    def post(self, request, *args, **kwargs):
        text = request.data["text"]
        user = request.user
        post = Post(text=text, author=user)
        try:
            post.save()
            post =  PostSerializer(post).data
            return Response(post, status=200)
        except:
            return HttpResponse(status=400)
        

class LikeView(APIView):

    def post(self, request, *args, **kwargs):
        post_id = request.data["post"]
        comment_id = request.data.get("comment", None)
        user = request.user
        post = Post.objects.get(id=post_id)
        like = post.likes.filter(user=user, comment=comment_id, post=post)
        if like.exists():
            like.delete()
            return Response({"liked": False}, status=200)
        else:
            like = Like(post=post, user=user, comment=comment_id)
            like.save()
            return Response({"liked": True}, status=200)
        

class ProfileView(TemplateView):
    template_name = 'core/profile.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        perfil = Perfil.objects.get(user=self.request.user)
        ctx['photo'] = perfil.foto
        
        return ctx

network/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Network | {% block title %}{% endblock %}</title>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Vue.js -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.14/dist/vue.min.js"></script>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- BootstrapVue CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-vue@2.21.2/dist/bootstrap-vue.min.css" rel="stylesheet">

    <!-- Axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios@0.27.2/dist/axios.min.js"></script>

    <!-- Bootstrap and BootstrapVue JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-vue@2.21.2/dist/bootstrap-vue.min.js"></script>

</head>
<body>
    <div id="navbar">
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:home' %}">Network</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav me-auto">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Início</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'core:home' %}">Sobre</a>
                </li>
              </ul>
              <!-- Exibe o nome do usuário -->
              <span class="navbar-text">
                {% if user.is_authenticated %}
                Bem-vindo, {{ user.username }}!
                {% csrf_token %}
              </span>
              {% else %}
                <p>Please <a href="{% url 'core:login' %}">login</a> to see this page.</p>
              {% endif %} 
            </div>
          </div>
        </nav>
      </div>
    {% block content %}{% endblock %}
    {% block javascript %}{% endblock %}
</body>
</html>

network/templates/core/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Home</h1>

    <!-- Novo Post -->
    <div class="card shadow-sm mb-4">
        <div class="card-header bg-primary text-white">
            <h3 class="mb-0">Novo Post</h3>
        </div>
        <div class="card-body" id="newpost">
            <div class="input-group">
                <input type="text" class="form-control" name="text" placeholder="O que você está pensando?" v-model="text">
                <div class="input-group-append" v-if="text">
                    <button class="btn btn-primary" @click="newpost">Postar</button>
                </div>
            </div>
        </div>
    </div>

    <div id="posts">
        {% verbatim %}
        <div v-for="post in posts" :key="post.id" class="card mb-3 shadow-sm">
            <div class="card-body">
                <h5 class="card-title">{{ post.author_name }}</h5>
                <p class="card-text">{{ post.text }}</p>
                <p class="card-text">
                    <small class="text-muted">{{ post.date_formatada }}</small>
                </p>

                    <button 
                    class="btn btn-success" 
                    :disabled="post.liked == true" 
                    @click="sendLike(post.id, true)">
                    Like
                </button>
                <button 
                    class="btn btn-danger" 
                    :disabled="post.liked == false" 
                    @click="sendLike(post.id, false)">
                    Dislike
                </button>
                <span>{{ post.likes_num }}</span>
            </div>
        </div>
        {% endverbatim %}
    </div>
</div>

{% endblock %}

{% block javascript %}
    <script>
        var posts = {{ posts|safe }};
        var newpost = new Vue({
            el: '#newpost',
            data: {
                text: '',
            },
            methods: {
                getCookie() {
                    const match = document.cookie.match(/(^|;\s*)csrftoken=([^;]+)/);
                    return match ? match[2] : null;
                },
                newpost() {
                    const url = "{% url 'core:newpost' %}"

                    axios.post(url, {
                        'text': this.text}, { headers: { 'X-CSRFToken': this.getCookie() }}
                    )
                    .then(function (response) {
                        this.posts.push(response.data);   
              
                    })
                    .catch(function (error) {
                        console.log(error);
                    });
                    this.text = ''
                },                
            },
            mounted() {
            }
        })
        var post = new Vue({
            el: '#posts',
            data: {
                posts: []
            },
            methods: {
                setPosts() {
                    this.posts = posts
                },
                getCookie() {
                    const match = document.cookie.match(/(^|;\s*)csrftoken=([^;]+)/);
                    return match ? match[2] : null;
                },
                sendLike(id) {
                    const url = "{% url 'core:like' %}"
                    const obj = {
                        'post': id,
                        'comment': null
                    }
                    axios.post(url, obj, { headers: { 'X-CSRFToken': this.getCookie() }}
                    )
                    .then(function (response) {
                        if(response.status == 200) {
                            this.posts.forEach(post => {
                                if(post.id == id) {
                                    if(response.data.liked) {
                                        post.likes_num += 1                                        
                                    }
                                    else {
                                        post.likes_num -= 1
                                    }
                                    post.liked = !post.liked
                                }
                            });
                        }  
                    })
                    .catch(function (error) {
                        console.log(error);
                    });
                }
            },           
            mounted() {
                this.posts = posts
            }
        })
    </script>
{% endblock %}

network/templates/core/login.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Register</title>
</head>
<body>
    {% if form.errors %}
    {{ form.non_field_errors }} 
    {% endif %}

    <div class="d-flex justify-content-center align-items-center">
        <div class="col-12 col-md-8 col-lg-6">
            <form method="post" class="p-4 border rounded bg-light shadow" action="{% url 'core:login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label class="form-label font-weight-bold" for="username">Digite seu e-mail ou usuário</label>
                    <input class="form-control" type="text" name="username">
                    
                </div>
            
                <div class="form-group">
                    <label class="form-label font-weight-bold" for="password1">Digite a sua senha</label>
                    <input class="form-control" type="password" name="password">
                </div>
            
            
                <button type="submit" class="btn btn-primary btn-block font-weight-bold mt-3">Entrar</button>
            </form>
            <p>Novo por aqui? <a href="{% url 'core:register' %}">Registre-se</a></p>
        </div>
    </div>
</body>
</html>

network/templates/core/perfil_form.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block title %}Home{% endblock %}

{% block content %}
<div class="d-flex justify-content-center align-items-center">
    <div class="col-12 col-md-8 col-lg-6">
        <h2>Criar Perfil</h2>
        {% if user.is_authenticated %}

        <form action="{% url 'core:perfil_form' %}" method="post" class="form">
            {% bootstrap_form_errors form %}
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="hidden" name="id" value="{{ form.user.value }}" hidden>
            {% buttons %}
                <button type="submit" class="btn btn-primary">Salvar</button>
            {% endbuttons %}
        </form>
        {% else %}
            <p>Please <a href="{% url 'core:login' %}">login</a> to see this page.</p>
        {% endif %}
    </div>
</div>
{% endblock %}

network/templates/core/register.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Register</title>
</head>
<body>
    
    <div class="d-flex justify-content-center align-items-center">
        <div class="col-12 col-md-8 col-lg-6">
            <form method="post" class="p-4 border rounded bg-light shadow">
                {{ form.errors }} 
                {% csrf_token %}
                
                <div class="form-group">
                    <label class="form-label font-weight-bold" for="username">Digite seu usuário</label>
                    <input class="form-control" type="text" name="username" required>
                </div>

                <div class="form-group">
                    <label class="form-label font-weight-bold" for="email">Digite seu e-mail</label>
                    <input class="form-control" type="text" name="email" required>
                    
                </div>

                <div class="form-group">
                    <label class="form-label font-weight-bold" for="password1">Digite a sua senha</label>
                    <input class="form-control" type="password" name="password1" required>
                </div>

                <div class="form-group">
                    <label class="form-label font-weight-bold" for="password2">Digite novamente a senha</label>
                    <input class="form-control" type="password" name="password2" required>
                </div>

                <button type="submit" class="btn btn-primary btn-block font-weight-bold mt-3">Registrar</button>
            </form>
        </div>
    </div>
</body>
</html>